spring:
  application:
    name: gifpt
  config:
    import: "classpath:application-dotenv.properties"
  datasource:
    url: jdbc:mysql://localhost:3306/gifpt
    username: root
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gifpt:
  jwt:
    secret: "dev_dev_dev_dev_dev_dev_dev_dev_32bytes_min"
    expires-in-ms: 3600000  #1시간

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
